#!/bin/sh

run() {
  bin=$(whereis $1 | awk '{print $2}')
  if [ ! -z $bin ] && [ -x $bin ]; then
    pidof $1 && kill -9 $(pidof $1)
    sleep .2
    eval $bin
  fi
}

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 6

bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer false

bspc config normal_border_color "#6e6a86"
bspc config focused_border_color "#c4a7e7"
bspc config active_border_color "#eb6f92"

floating_window_size="720x428+323+180"

# winow rules
bspc rule -a "Thunar" state=floating rectangle=$floating_window_size
bspc rule -a "Localsend" state=floating
bspc rule -a "papers" state=floating
bspc rule -a "feh" state=floating

xsetroot -cursor_name left_ptr

run polybar &
run sxhkd &
run fusuma &
